//
//  GreetingInteractor.swift
//  GreetingApp
//
//  Created by Alexey Turulin on 9/28/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol GreetingBusinessLogic {
    func doSomething(request: Greeting.ShowGreeting.Request)
}

protocol GreetingDataStore {
    
}

class GreetingInteractor: GreetingBusinessLogic, GreetingDataStore {
    
    var presenter: GreetingPresentationLogic?
    var worker: GreetingWorker?
    
    func doSomething(request: Greeting.ShowGreeting.Request) {
        worker = GreetingWorker()
        worker?.doSomeWork()
        
        let response = Greeting.ShowGreeting.Response()
        presenter?.presentSomething(response: response)
    }
}
