//
//  GreetingPresenter.swift
//  GreetingApp
//
//  Created by Alexey Turulin on 9/28/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol GreetingPresentationLogic {
    func presentGreeting(response: GreetingResponse)
}

final class GreetingPresenter: GreetingPresentationLogic {
    
    weak var viewController: GreetingDisplayLogic?
    
    func presentGreeting(response: GreetingResponse) {
        let greeting = "Hello, \(response.name) \(response.surname)!"
        let viewModel = GreetingViewModel(greeting: greeting)
        viewController?.displayGreeting(viewModel: viewModel)
    }
}
