//
//  GreetingInteractor.swift
//  GreetingApp
//
//  Created by Alexey Turulin on 9/28/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol GreetingBusinessLogic {
    func showGreeting(request: GreetingRequest)
}

protocol GreetingDataStore {
    var person: Person? { get }
}

final class GreetingInteractor: GreetingBusinessLogic, GreetingDataStore {
    
    var presenter: GreetingPresentationLogic?
    var person: Person?
    
    func showGreeting(request: GreetingRequest) {
        person = Person(name: "Tim", surname: "Cook")
        let response = GreetingResponse(name: person?.name ?? "", surname: person?.surname ?? "")
        presenter?.presentGreeting(response: response)
    }
}
