//
//  GreetingPresenter.swift
//  GreetingApp
//
//  Created by Alexey Turulin on 9/28/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol GreetingPresentationLogic {
    func presentSomething(response: Greeting.ShowGreeting.Response)
}

class GreetingPresenter: GreetingPresentationLogic {
    
    weak var viewController: GreetingDisplayLogic?
    
    func presentSomething(response: Greeting.ShowGreeting.Response) {
        let viewModel = Greeting.ShowGreeting.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
