//
//  GreetingWorker.swift
//  GreetingApp
//
//  Created by Alexey Turulin on 9/28/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

final class GreetingConfigurator {
    static let shared = GreetingConfigurator()
    
    private init() {}
    
    func configure(with viewController: GreetingViewController) {
        let interactor = GreetingInteractor()
        let presenter = GreetingPresenter()
        
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
}
